Better tooltips
sul-cidr/pianolatron pull request #103
Opened 2021-09-16 16:37 UTC by simonwiles

This PR replaces the simple CSS-based tooltips with something that depends on Javascript instead.

The primary motivation for this is the need to anchor the tooltip elements to the highest part of the DOM tree as possible (`document.body` in this case) and then position them appropriately, so as to alleviate clipping context issues.

Right now the behaviour is like-for-like (with the above exception), but this will allow other improvements such as HTML tooltips, automatic flipping and positioning, and overflow-prevention to be added very easily if/when we need them.

In a departure from my usual MO, this functionality leans on popper to do all the heavy lifting (so a `yarn install` will be required after checking out this branch).  For this very simple application only the smallest amount of popper's range of functionality is required; for this reason the minimum amount of library code is imported, but it still adds ~3.5K to the shipped bundle.  However, the point is to be as close to bullet-proof as possible and not spend ages chasing edge cases, and popper as a positioning library is a solid as it gets in this respect.  Adding tooltips to other parts of the application should be more straightforward this way.

2021-09-16 19:10 UTC, broadwell requested changes
I'm totally cool with using Popper for this, and the new tips look good. Probably we should address the issue with the reset buttons before merging, though.

2021-09-16 19:10 UTC, broadwell commented on src/components/KeyboardShortcutEditorRow.svelte
> +    use:tooltip={shortcut.isChanged ? "Reset to Default" : undefined}
These props seem to be handled differently under the Popper regime. Here's what the tooltip looks like for the reset button on a key binding that has never been changed from the default:
![Screen Shot 2021-09-16 at 12 03 12 PM](https://user-images.githubusercontent.com/7329112/133670522-b5516fbf-3b52-41f3-b2e8-8970db7121de.png)
Note also that the "Reset to Default" text persists for a binding that has been reset, until the Keyboard Controls popup is closed and reopened:
![Screen Shot 2021-09-16 at 12 04 44 PM](https://user-images.githubusercontent.com/7329112/133670719-5481350d-8144-4866-aec1-c786ac2e4b45.png)
In this case, the simplest fix is just to remove the tooltip entirely, since it should be pretty obvious what the button does. But a more systematic fix probably involves some tweaks to the tooltip code.

2021-09-16 19:23 UTC, broadwell commented on src/components/KeyboardShortcutEditorRow.svelte
> +    use:tooltip={shortcut.isChanged ? "Reset to Default" : undefined}
And yikes, the behavior is different on Opera (Mac OS). The `undefined` value for the `text` parameter results in an absent tooltip, which is fine, but once the key has been remapped, the tooltip looks like this:
![Screen Shot 2021-09-16 at 12 14 06 PM](https://user-images.githubusercontent.com/7329112/133671621-c0bacac1-0eeb-487c-bd0f-ebe2ee0f473b.png)
and as above, the "undefined" tooltip hangs around after the reset button has been clicked.

2021-09-23 16:56 UTC, simonwiles commented on src/components/KeyboardShortcutEditorRow.svelte
> +    use:tooltip={shortcut.isChanged ? "Reset to Default" : undefined}
I've not been able to reproduce either of these behaviours exactly (presumable for want of a Mac, and Opera especially), but I've just pushed some updates that improve the way the tooltips are bound, and hopefully they'll address this.  Behaviour is solid on FF, Chromium, and Opera on Linux and Windows 10 in VM -- could you give it a spin for me?

2021-09-23 18:07 UTC, broadwell commented
Great, these updates fix the tooltip behavior on Mac OS Firefox and Chrome. I think this is ready to merge.

2021-09-23 18:09 UTC, merged